### ISSUE TITLE
openvanilla does not work on macOS 10.12.1

### ISSUE THREAD

**Issue by chiumichael** [openvanilla/openvanilla#13]
Tried reinstalling and (removed according the homepage instructions, restarted and reinstalled). Still grey-ed out for all applications.

**Comment by lukhnos** [comment]
Which version of OpenVanilla did you try to reinstall?

**Comment by chiumichael** [comment]
Thanks for the quick reply, lukhnos, 1.1.0

**Comment by lukhnos** [comment]
Does your machine have any security software installed, or is it under some corporate security policy (like a managed machine)?

Also, do you have a very old OpenVanilla somewhere else, such as in `/Library/Input Methods` (which is different from the one in your home, `~/Library/Input Methods`)?

My OV 1.1.0 runs fine on macOS 10.12.1 but I do get occasional reports that it doesn't work, though it's the first time I hear it doesn't work with *any* application, so we'd need more information to find the possible causes. Thanks!

**Comment by chiumichael** [comment]
Nope, not security software installed -- it's a personal machine.

I also do not have an old copy anywhere (at least I don't think so). Definitely not in the directories you've listed above.

**Comment by lukhnos** [comment]
That's strange then. What is your system's default language? English, Traditional Chinese (TW? HK?), Simplified Chinese?

Also if it's not too much a trouble, could you open your Console.app, click on the "Diagnostic and Usage Data" item on the left, and use the search field to look for "OpenVanilla", and see if there is anything that looks suspicious?

When I did that, this is what I saw:

```
13:29:56.974948 -0800	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: OpenVanilla
com.apple.message.signature2: org.openvanilla.inputmethod.OpenVanilla ||| 1.1.0 (3180)
com.apple.message.value: 6
com.apple.message.value2: 0
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 0
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: [redacted]
```

Which looks right to me. But I was wondering if you'd see things other than that.

**Comment by chiumichael** [comment]
The default/primary is English.

I get something slightly different, but nothing suspicious, imo
```com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature2: org.openvanilla.inputmethod.OpenVanilla ||| 1.1.0 (3180)
com.apple.message.value: 0
com.apple.message.value2: 0
com.apple.message.value3: 1
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 0
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: [redacted]```

**Comment by chiumichael** [comment]
Nice! 得咗喇！

OV was working before upgrading to macOS 10.12.x (old laptop, 2014mbp), but I had _lots_ of times when it was disabled (greyed out) for almost everything.

I mostly use: sublime text, atom, emacs, whatsapp, slack, chrome, safari

Thanks so much for the help! Really appreciate it!
