### ISSUE TITLE
Chrome部份網頁無法使用香草輸入法

### ISSUE THREAD

**Issue by kudorori** [openvanilla/openvanilla#15]
在這兩個網頁的編輯器中，無法正常輸入，目前是測出Chrome有這個狀況，Safari則正常。

http://editor.swagger.io/#/

http://dillinger.io/

**Comment by lukhnos** [comment]
我目前認為這是這兩個網頁的 JavaScript editor 的問題（很多 JS-based editor 都有此問題）。原因是這樣的，我用小麥以及內建的注音及日文輸入法，都有這兩個 editor 無法正確處理的問題。好比說，用內建注音打「ㄓㄨˋㄧㄣ space」，等「注音」兩字出現後，按兩次 backspace，會發現只有「音」被刪除掉，而「注」沒有。

這代表這兩個 editor 可能都沒有正確處理某些 web 相關的 IME 事件，不過我因為很不熟 JS / DOM 這一部分領域的問題，只能就過往經驗來說，如果內建輸入法沒有完全正確的行為，在 OpenVanilla 也不會正確。而且因為 OV 輸入法的組字需求跟行為比內建複雜，更容易在與內建輸入法已不相容的 app 中出現其他問題。

所以得請你向這兩個網頁的開發者回報內建輸入法事件沒有正確處理的問題。這張 bug 恐怕只能列為 Won't Fix 了。
