### ISSUE TITLE
選字框在某些小視窗不會自動調節位置

### ISSUE THREAD

**Issue by nycching** [openvanilla/openvanilla#17]
選字框在某些小視窗不會自動調節位置
更新後在小視窗若需要打字時
選字框會自動縮小要用mouse移動才可以看到餘下部分選字
十分不便
更新前不會有此問題
![2017-01-17 3 45 50](https://cloud.githubusercontent.com/assets/25169594/22011955/a26fd982-dccc-11e6-88ea-629704ebc415.png)

**Comment by lukhnos** [comment]
看來這是 1.3.0 版目前最大的問題 (參見 #16)。倒是如果改裝回 1.2.0 版（下載連結: https://github.com/openvanilla/openvanilla/releases/tag/1.2.0 ) 就沒問題嗎？

如果要裝 1.2.0 版，安裝完後請登出，並用「關於 OpenVanilla」確認版本。這樣可以幫助我們 debug。謝謝！

**Comment by lukhnos** [comment]
Hi, 我們剛剛製作了 1.3.1 版，下載連結在: https://github.com/openvanilla/openvanilla/releases/tag/1.3.1

雖然我認為你的問題跟 #16 可能不完全一樣，但是否可以試試看 1.3.1 有無此問題？

若仍有此問題，就得請你試試看先前版本（例如 1.2.0 或更早版本），看看是哪個版本開始有問題的了。

**Comment by nycching** [comment]
1.2.0版本沒有問題 應該是1.3.0版本才出現問題的

**Comment by lukhnos** [comment]
Ok, 那請你再提供以下資訊：

* 是所有的應用程式都這樣？還是只有少數或一個應用程式有此問題？
* 是哪些/哪個應用程式？
* 你用的 macOS 版本？用哪一種 OV 輸入法？
* 出現此問題時，視窗在全螢幕模式？還是普通大小？有接近螢幕邊緣嗎？

**Comment by nycching** [comment]
我目前只發現telegram發生此問題
mac os10.11.6
我用的是簡易
出現此問題時，視窗在普通大小，有接近螢幕邊緣


2017-01-18 22:52 GMT+08:00 Lukhnos Liu <notifications@github.com>:

**Comment by daihakken** [comment]
我也發現了這個問題，我在使用ov的速成輸入法
<img width="194" alt="screen shot 2017-01-19 at 14 34 23" src="https://cloud.githubusercontent.com/assets/13048125/22096059/5d15ab4e-de54-11e6-93dd-8d0746e9d5b7.png">

**Comment by lukhnos** [comment]
可否請各位試試看 1.3.2 版？下載網址在 https://github.com/openvanilla/openvanilla/releases/download/1.3.2/OpenVanilla-Installer-Mac-1.3.2.zip

如果 1.3.2 版修正了這個問題，我會正式發布。謝謝！

**Comment by lukhnos** [comment]
Fixed in 1.3.2.
