### ISSUE TITLE
優化刪除輸入碼

### ISSUE THREAD

**Issue by etang77** [openvanilla/openvanilla#18]
先再說一聲非常感謝解決了用Shift鍵選字的問題！

因為我是用快碼的所以以為是我的輸入碼問題，但我也用了其他輸入法來試了一下，也發現有同一個小問題，就是刪除輸入碼時會變成了打第一選擇字。

例子如下：
用快碼，我打「/AA」就會題示出「我人人」，第一選擇就是「從」字，我按space bar就會打出「從」字。這很正常的。

但不正常的地方是，比如我輸入了「我人人」後，才發現我要打的字不是在這個輸入碼裡頭，按delete，他就不理會我是想刪除，直接把「從」字打出。

**Comment by lukhnos** [comment]
謝謝你回報，這其實是修正 #3 時的疏忽，造成的 regression。也是因為有你協助測試，讓這個 regression 能被早期發現。

已經在[這個 commit](de6e0e336d41e5a2891ab2f5e6a4ff7e58d6e2d0) 修正，請試試看用 git 取得最新 master，重新 build OpenVanillaInstaller 並安裝新版看看。

**Comment by lukhnos** [comment]
Fixed in 1.3.2.
