### ISSUE TITLE
Is it possible to wrap around the text selection window?

### ISSUE THREAD

**Issue by peteroid** [openvanilla/openvanilla#19]
### Issue
For Simplex input method, the selection window is usually long ( >5 pages ). If the expected word locating at the last page, we have to press `space`or `right arrow key` many times to reach the last page to get the word. 

### Solution
1. press `left arrow key` on the first page could go to the last page
2. press `up arrow key` on the first element of the first page, could go to the last element of the last page

**Comment by zonble** [comment]
rev 37f2d7f954f6436839c2e8995aabede77a139ca0 修正。
