### ISSUE TITLE
Overwriting a table doesn't work

### ISSUE THREAD

**Issue by michaelwills** [openvanilla/openvanilla#2]
Creating an issue as requested in #1.

If you create a new `.cin` file, populate it, add it, and then modify the file and choose "add again", the dialogue says it will overwrite the existing table. However the changes do not take effect and you have to remove the table first and then add it again.

This is noted in #1 along with the workaround that to dynamically update it, update the file stored in Application Support, i.e. `/Library/Application Support/OpenVanilla/UserData/TableBased/example.cin`.

**Comment by lywinged** [comment]
Yah, that's the "replace" and "copy" path issue, you can add     _[[NSFileManager defaultManager] removeItemAtPath:targetPath error:NULL];_ before the _BOOL success = [[NSFileManager defaultManager] copyItemAtPath:path toPath:targetPath error:&error];_ in the OVModuleManager.mm.

**Comment by zonble** [comment]
rev 57471dd049c76dcfbc48a84fb0b3b7240b6b7d87 修正。
