### ISSUE TITLE
新版香草改 .cin 方式不同？

### ISSUE THREAD

**Issue by KIRINPUTRA** [openvanilla/openvanilla#21]
小弟長期使用 OSX 10.9 和香草 1.0.x、主要是打倉頡。也自己到香草的檔案內修改 cj.cin、像替「々」和注音符號設碼、替「　」「、」設單鍵碼、在 .cin 較前面重設「引」字等（因爲比「弔」更常打、想讓他「置頂」）。

最近更新成 OSX 10.12 以及香草 1.3.3、發現改香草內建 cj.cin 無效。複製另存再加入新輸入法（即改過的 cj.cin）也無效（仍然一如內建 cj.cin、「々」和注音符號打不出來等）。

想請問是哪一項作業需要調整？謝謝。

**Comment by KIRINPUTRA** [comment]
找到方法解決了。

**Comment by lukhnos** [comment]
可否分享一下，當初為何修改無效，後來是怎麼解決的？

**Comment by KIRINPUTRA** [comment]
第一、我單純將字碼在 .cin 檔中放錯區塊。

第二、之前用 OSX 10.9 及香草 1.0.x 時、是直接修改香草內建 cj.cin 檔、存檔後則立即生效。升級 macOS 10.12 之後、無論香草 1.3.3 或 1.1.0、那樣的流程無效。必須另存 .cin 檔、然後「加入新輸入法」。有修改的話、必須「移除輸入法」→ 重新「加入新輸入法」。我現在在用 1.1.0。
