### ISSUE TITLE
選字視窗介面的一些小問題

### ISSUE THREAD

**Issue by andrewwutw** [openvanilla/openvanilla#23]
在選字視窗介面，如果候選字超過一頁，不會顯示總共有幾頁可以選，以及目前顯示的是第幾頭，另外空白鍵只能跳到下一頁，最後不會跳回第一頁。

例如 : 用「簡易輸入法」，輸入 QQ (手手)，畫面會顯示選字視窗 :

<img width="324" alt="2017-11-24 6 14 57" src="https://user-images.githubusercontent.com/4443713/33207767-f251d3b6-d149-11e7-9be1-91c7c0ddd3a5.png">

雖然可以從 ">>" 這個按鈕的存在，判斷有下一頁候選字，但是無法知道候選字全部有幾頁。

按下空白鍵，可以換到下一頁，但是無法知道目前是在第幾頁。

<img width="308" alt="2017-11-24 6 15 09" src="https://user-images.githubusercontent.com/4443713/33207813-183ac114-d14a-11e7-94b4-24754a00eeff.png">

<img width="311" alt="2017-11-24 6 15 17" src="https://user-images.githubusercontent.com/4443713/33207826-26961060-d14a-11e7-86ed-76b6cb04ae5f.png">

到達最後一頁時，可以由 ">>" 這個按鈕顏色變淡得知，但是此時如果再按下空白鍵

<img width="255" alt="2017-11-24 6 15 26" src="https://user-images.githubusercontent.com/4443713/33207839-3676970c-d14a-11e7-8356-8bdbc65cbe31.png">

<img width="255" alt="2017-11-24 6 15 31" src="https://user-images.githubusercontent.com/4443713/33207853-443b76dc-d14a-11e7-8082-d34366fd6c85.png">

也只是將游標移動到最後，之後再按空白鍵，也不會跳回第一頁，如果想要回到之前的候選字頁，只能用方向鍵的「左」，慢慢的移回去，操作上十分不便。

在 Yahoo 奇摩輸入法裡，行為就比較合理一點。有多頁候選字時，會顯示目前是第幾頁 :

<img width="541" alt="2017-11-24 6 16 14" src="https://user-images.githubusercontent.com/4443713/33207871-5a79fa18-d14a-11e7-9887-372667782a77.png">

<img width="537" alt="2017-11-24 6 16 21" src="https://user-images.githubusercontent.com/4443713/33207873-60374afa-d14a-11e7-8a7b-6bb992dfed13.png">

同時，在到達最後一頁的情形下，再按空白鍵，就會跳回第一頁，在選字時會比較容易一點

如果可能的話，希望能改成這樣的操作介面。

**Comment by zonble** [comment]
rev 37f2d7f954f6436839c2e8995aabede77a139ca0 修正
