### ISSUE TITLE
打錯字碼沒有正確清除 reading buffer 

### ISSUE THREAD

**Issue by puritys** [openvanilla/openvanilla#24]
我同時打開 ClearReadingBufferAtCompositionError 跟 ComposeWhileTyping 這兩個功能，發現 ClearReadingBufferAtCompositionError 會失效， 造成我打錯字碼的時候，無法自動清除當前的 reading buffer.

看了一下程式，這兩個功能是相衝突的 。

https://github.com/openvanilla/openvanilla/blob/641806d79cae7ecf440300182c732f458b09a82f/Modules/TableBased/OVIMTableBasedContext.cpp#L351

```

        if (!m_module->m_configComposeWhileTyping && m_module->m_configClearReadingBufferAtCompositionError) {
            m_components.clear();
            readingText->clear();
            readingText->updateDisplay();
            return false;
        }

```

**Comment by puritys** [comment]
我發了一個  PR ，當 user 輸入 Space or Return ，代表他已經輸入完畢，接下來之會有兩個結果
1. 成功，組合出字根
2. 失敗，沒有 match 任何字根。

當我 enable  ClearReadingBufferAtCompositionError  時，兩個結果都應該要清除 reading buffer.
https://github.com/openvanilla/openvanilla/pull/25

**Comment by lukhnos** [comment]
剛剛從 master 編了 OpenVanillaInstaller，安裝之後，確認在 `m_configComposeWhileTyping` 以及 `m_configClearReadingBufferAtCompositionError` 同時為真的情況下，輸入無效字根按 Space 組字時，組字區會正確清除了。感謝！
