### ISSUE TITLE
OpenVanilla 行列輸入法鍵碼表 0.85 版

### ISSUE THREAD

**Issue by gontera** [openvanilla/openvanilla#26]
本版新增支援 CJK Ext-F 字集範圍（Unicode 內碼範圍 2CEB0~2EBE0），請協助納入更新，謝謝。

**Comment by gontera** [comment]
抱歉一時沒注意，Ext-F 鍵碼放反了，請以 0.86 版為主，謝謝。
[array30_OpenVanilla_0.86.cin.zip](https://github.com/openvanilla/openvanilla/files/1941562/array30_OpenVanilla_0.86.cin.zip)

**Comment by lukhnos** [comment]
檢查了一下 .cin 檔，發現裡面的 `%kefdef` 跟 `%chardef` 段落裡面都有 `#` 開頭的註解。我沒記錯的話 OV 是不接受這兩個段落裡面的註解的，先前 OV 的 `array30.cin` 檔註解也僅限於檔案開頭。可否請老刀兄檢查一下是否真是如此？

**Comment by gontera** [comment]
Dear Lukhnos,

 

好久不見！

 

打 # 註解，只是為了方便我製作各種 CJK Extension 方便而已，在 OpenVanilla 中，即使在 %chardef 中加上註解也是不會影響使用（我套用 0.86 版 array30.cin 在 OV 很久了，可以正常使用沒有問題），如果您覺得礙眼，將這些註解去除當然也是可以的。

 

老刀

 

寄件者: Lukhnos Liu <notifications@github.com>
回覆: openvanilla/openvanilla <reply@reply.github.com>
日期: 2018年11月26日 星期一 上午12:57
收件者: openvanilla/openvanilla <openvanilla@noreply.github.com>
副本: Gontera Yeh <gontera@gmail.com>, Author <author@noreply.github.com>
主旨: Re: [openvanilla/openvanilla] OpenVanilla 行列輸入法鍵碼表 0.85 版 (#26)

 

檢查了一下 .cin 檔，發現裡面的 %kefdef 跟 %chardef 段落裡面都有 # 開頭的註解。我沒記錯的話 OV 是不接受這兩個段落裡面的註解的，先前 OV 的 array30.cin 檔註解也僅限於檔案開頭。可否請老刀兄檢查一下是否真是如此？

**Comment by lukhnos** [comment]
Ok, 既然 `#` 註解列不影響行列正常使用，那就沒問題了。下一版 OV 會收納這個版本的表格，謝謝！

**Comment by lukhnos** [comment]
新版表格已隨 1.4.0 版發布: https://github.com/openvanilla/openvanilla/releases/tag/1.4.0
