### ISSUE TITLE
Input method shortcut failed to switch to/from openvanilla within 4 secs from last switch

### ISSUE THREAD

**Issue by ghost** [openvanilla/openvanilla#29]
I've been experienced this for a while since upgraded to macOS 10.13. As I switch from/to openvanilla (v 1.3.4) frequently, this issue has been bugging.

If the input method switch (ctrl+space) event is more than 4 secs after the last one, it switches fine to/from openvanilla. If less then 4 secs, the key combination (ctrl+space) would fail and lock. More attempts wouldn't have any effect. When I cmd+tab to another application and cmd+tab back, the key combination works again. But again if next attempt is within 4 secs, it locks.

I tried to provide more useful information, though I don't see any logged entries on Console?

Any hints would be appreciated.

**Comment by lukhnos** [comment]
Could you let us know if this happens to you across all apps, or does this only happen to one / a few apps that you use? Do you have any utilities (text expander, etc.) installed?

**Comment by scsonic** [comment]
I have the same problem about switch input method too (using the newest version with macos 11.5.1), how can I get the openvanilla log? like grep "openval" in system file ?

**Comment by lukhnos** [comment]
> I have the same problem about switch input method too (using the newest version with macos 11.5.1), how can I get the openvanilla log? like grep "openval" in system file ?

First of all, does this happen every time, all the time? Or does this happen only under certain circumstances, for example, right after restarting and switching to OpenVanilla while other apps are being loaded?

Second, it would be helpful to look at if there are any relevant OpenVanilla log lines. If you open Console.app, then go to the menu Action > Start Streaming, and then enter OpenVanilla in the search bar at the top right corner, you should be able to see relevant log lines start appearing shortly.
