### ISSUE TITLE
%selkey cannot specify characters that needs shift key to access

### ISSUE THREAD

**Issue by sltam** [openvanilla/openvanilla#3]
I have these config in my .cin file:

```
%gen_inp
...
%selkey !@#$%^&*()
...
%keyname begin
...
```

When I put this cin file into OpenVanilla 1.0.x, and type anything that has disambiguation, it shows `!`, `@`, etc. on top of the choices, but when I hit `shift-1`, `shift-2`, etc. OpenVanilla unexpectedly cancels the current composition and emits the `!` character! This renders my input method completely unusable!

This does not happen to OpenVanilla 0.8.x.

Before:
![2014-05-24 21 39 41](https://cloud.githubusercontent.com/assets/51615/3074623/ee788fd4-e348-11e3-9962-d555774ea7b1.png)

After hitting "!":
![2014-05-24 21 40 05](https://cloud.githubusercontent.com/assets/51615/3074624/f7a869da-e348-11e3-9bbb-d0a49bfb8193.png)

**Comment by etang77** [comment]
Have anyone been able to fix this?

Or does anyone know where to edit in the code to change this?

**Comment by sltam** [comment]
@etang77 My guess is [OVInputMethodController](https://github.com/lukhnos/openvanilla/blob/master/Source/Mac/OVInputMethodController.mm#L312) and [OVOneDimensionalCandidatePanelImpl](https://github.com/lukhnos/openvanilla/blob/master/Source/Mac/FrameworkImpls/OVOneDimensionalCandidatePanelImpl.mm#L443),  but since I am not affiliated to this project, I don't know how to start helping. I can't even get my self-compiled library to run locally yet.

**Comment by etang77** [comment]
I've seen that assocation phrases has in its script, allow to use Shift + Symbols as select key, and display as an "Up arrow 1".   I'm shure it can work for the normal select key too, anyone can teach me how to edit?

**Comment by lukhnos** [comment]
@sltam @etang77 If you use Xcode, could you try building the target "OpenVanillaInstaller" in [the latest master](https://github.com/openvanilla/openvanilla/commits/master) (open `OpenVanilla.xcodeproj` in the repo root), and use the installer to install a dev version (1.3.2-dev) on your machine? The commit should fix this long-standing issue. Thanks!

**Comment by etang77** [comment]
Thank you, I'll try.

**Comment by etang77** [comment]
Thank you, so so so so much!  Everything fixed (I think)!

**Comment by etang77** [comment]
Being greedy here.  Is it possible for the interface to show "Shift1"、"Shift2" like in Associated Phrase?
