### ISSUE TITLE
Bug in Simplex with "use space as the first candidate key"

### ISSUE THREAD

**Issue by vngvng** [openvanilla/openvanilla#30]
OpenVanilla Version: 1.3.4 (3242)
When using Simplex, normally the candidate list contain 9 items only for each page.

![screen shot 2018-08-24 at 10 53 17](https://user-images.githubusercontent.com/24654786/44562409-0c64e900-a78c-11e8-8768-fb17d4c9b1ff.png)

Reproduce the issue:
Go to preferences and checked "use space as the first candidate key"

![screen shot 2018-08-24 at 10 55 22](https://user-images.githubusercontent.com/24654786/44562478-5d74dd00-a78c-11e8-9313-48ddb73ff67c.png)

Candidate list shows 10 items, the 1st item will start before 1.

![screen shot 2018-08-24 at 10 53 42](https://user-images.githubusercontent.com/24654786/44562414-171f7e00-a78c-11e8-90f3-c5b50201aa6b.png)

**Comment by zonble** [comment]
Actuallyt I do not know what do you expect. Do you mean there should be only 9 but 10 candidates when the option is on?

**Comment by zonble** [comment]
在 1.7 版當中，可以設定如果用第一個按鍵當作選字鍵的行為了。
