### ISSUE TITLE
行列輸入法無法上字

### ISSUE THREAD

**Issue by arthurhsu** [openvanilla/openvanilla#31]
Environment:

macOS Mojave 10.14.3
Macbook Pro 2018
OpenVanilla 1.4.0 (3250)

使用行列輸入法時某些字無法上字

哇哈哈 的 哈
不能 的 不

Tried both system's Note and Chrome

**Comment by lukhnos** [comment]
我在 macOS 10.14.4 的 Notes.app 以及在 Chrome 73.0.3683.103 上無法重現這個問題，#32 也提到行列在 Finder 搜尋列中無法出字。我試過的方法是：

* 在 Notes.app 或 Chrome 中打 `;i;` 以及 `hg` (出「哈」)，選字窗正常出現，選字後正常出字
* 在 Notes.app 或 Chrome 中打 `z` 以及 `ah` (出「不」)，選字窗正常出現，選字後正常出字

另外在偏好設定中試過開啟/關閉行列的兩種模式。我並非行列使用者，不過似乎符合預期行為（我只知道其中一個模式會提示較短的短碼或類似行為）。

恐怕需要更多 repro steps 看是否真的是 OV 行列的問題。

**Comment by arthurhsu** [comment]
Repro video: https://youtu.be/7sY889ll_eQ

**Comment by lukhnos** [comment]
影片連結失效。我剛收到時在手機上看，症狀看來是在打了一連串字後，中間如果有輸入錯誤，那再重打那串字，中間就有一些字出不來。

我不是行列使用者，如果要 repro 超過單字以上的輸入，請提供完整的 key sequence。

**Comment by arthurhsu** [comment]
影片應該是可以打開的，測試的結果發現若勾選了 Enforce special code ("Quick Mode" or Force SP) 則行列輸入法無法上字

測試的字串
"打不出來" "oad1z dd vkk "

**Comment by gontera** [comment]
> 影片應該是可以打開的，測試的結果發現若勾選了 Enforce special code ("Quick Mode" or Force SP) 則行列輸入法無法上字
> 
> 測試的字串
> "打不出來" "oad1z dd vkk "

結論是：你勾選了「強迫使用特別碼」的「快打模式」，然後抱怨你打不出字（因為你不是輸入它的特別碼，本來就不會上字）。

**Comment by zonble** [comment]
隨著 #77 已被修正（在 #83 修正），應該可以一起關掉這張票。

**Comment by zonble** [comment]
隨著 #77 已被修正（在 #83 修正），應該可以一起關掉這張票。
