### ISSUE TITLE
在最新版MS office 上不能用openvanilla

### ISSUE THREAD

**Issue by cliff-cc** [openvanilla/openvanilla#37]

**Comment by lukhnos** [comment]
我測試了 Word/Excel/PowerPoint 2019 (Version 16.25)，macOS 10.14.5 使用 OV 1.4.0 內建倉頡並無遇到問題。請提供 MS Office 版本、Office 哪個 app、macOS 版本、OV 版本、使用 OV 哪個輸入法，以便進一步診斷是否為 OV 的問題。

**Comment by Cliffhou** [comment]
Excel 16.26 (19060901)
OV 1.4.0
速成不能使用

**Comment by zonble** [comment]
無法重現…先關掉好了。
