### ISSUE TITLE
openvanilla的簡易輸入法 於pycharm上無法選取1－4的關聯字

### ISSUE THREAD

**Issue by oklpplko** [openvanilla/openvanilla#39]
如題

**Comment by lukhnos** [comment]
我在 macOS 10.14.6 上使用 OpenVanilla 1.4.0 簡易 + 聯想詞 + CLion 2018.3 可以重現這個問題 (CLion 跟 PyCharm 底層是同一套 IDE 架構)。問題不在於 Shift 1-4 無法選字，是 CLion 只接受長度超過一個字的聯想詞。

我恐怕得將這 bug 關閉，歸檔在「做不到」 / infeasible 這個類別。OV 在輸出完輸入法本身的選字，進入聯想詞模式的時候，應用程式的 input method composition buffer 已經清空了。我猜 PyCharm / CLion 的假定是輸入法在這狀態下，是不應該/不可能直接出 Unicode code point 長度只有 1 的 composition commit。

這個 bug 最終說來是 PyCharm/ CLion 的 bug.

**Comment by oklpplko** [comment]
多謝解答！！
