### ISSUE TITLE
“麻“字用簡易輸入法打唔到。

### ISSUE THREAD

**Issue by mmm117** [openvanilla/openvanilla#40]
“麻“字用簡易輸入法打唔到。

**Comment by tianjianjiang** [comment]
> “麻“字用簡易輸入法打唔到。

我用「戈金」可以看到「麻」在第二位。

**Comment by mmm117** [comment]
但用Mac的輸入法，應該是"戈木"才對啊。

**Comment by tianjianjiang** [comment]
> 但用Mac的輸入法，應該是"戈木"才對啊。

@mmm117 
倉頡三代和五代的字根一直都是「戈金」。而 macOS 內建輸入法不時有些錯誤。

**Comment by mmm117** [comment]
OK，謝謝！
