### ISSUE TITLE
深色模式下的行列提示框不易辨識

### ISSUE THREAD

**Issue by charleshs** [openvanilla/openvanilla#42]
行列輸入法的提示框（特別碼、查無字）在深色模式下，文字顏色變成白色，但被景色依舊是黃色。
在辨識上略有困難，不曉得有沒有方法可以修改，謝謝！

![image](https://user-images.githubusercontent.com/8415840/78498821-301d4d00-777f-11ea-8896-b878ed9c0e09.png)

**Comment by lukhnos** [comment]
Fixed in 1.6.0.

**Comment by charleshs** [comment]
Thanks for the fixing. Really appreciated!
