### ISSUE TITLE
行列輸入法簡碼表格更新

### ISSUE THREAD

**Issue by gontera** [openvanilla/openvanilla#44]
這版修正了 2^2v (wx) 的簡碼誤植（如附檔），敬請開發團隊儘速納入更新；這份更新檔案與本人的 github 空間的版本相同。
[array-shortcode-20201106.cin.zip](https://github.com/openvanilla/openvanilla/files/5504807/array-shortcode-20201106.cin.zip)

**Comment by lukhnos** [comment]
已經將表格整合進 1.6.1 版，剛剛已經發布了，謝謝！

https://github.com/openvanilla/openvanilla/releases/tag/1.6.1
