### ISSUE TITLE
關於聯想字排序

### ISSUE THREAD

**Issue by hoho97** [openvanilla/openvanilla#45]
習慣了windows速成／倉頡的聯想詞排序，想把openvanilla的聯想詞庫改成windows的順序，是不是只要把associated-phrases.cin修改一下就行了？

p.s.  "~/Library/Application Support/OpenVanilla/UserData/TableBased" 這資料夾裡面是空的，請問修改聯想字的cin後應該放到哪裡去？

**Comment by lukhnos** [comment]
哎呀，很不幸的，當初加入聯想詞支援的時候，把資料檔案的位置寫死了: https://github.com/openvanilla/openvanilla/blob/master/Source/Mac/OVModuleManager.mm#L264

我試了一下，如果直接修改 `~/Library/Input Methods/OpenVanilla.app/Contents/Resources/DataTables/AssociatedPhrases/associated-phrases.cin`，會讓 macOS 認為 `OpenVanilla.app` 損毀了 (簽章驗證工具會說 "a sealed resource is missing or invalid")。

要能夠自訂 `associated-phrases.cin` 的內容，有兩條途徑：

1. 要不就是自己裝 Xcode 然後 git clone OpenVanilla 的原始碼，自己編譯安裝，這樣想怎麼改就可以怎麼改
2. 修改 `OVModuleManager.mm` 或是 `OVAFAssociatedPhrases.cpp` 讓聯想詞模組可以在有 user override file 的情況下，優先採用用戶提供的檔案

**Comment by hoho97** [comment]
> 哎呀，很不幸的，當初加入聯想詞支援的時候，把資料檔案的位置寫死了: https://github.com/openvanilla/openvanilla/blob/master/Source/Mac/OVModuleManager.mm#L264
> 
> 我試了一下，如果直接修改 `~/Library/Input Methods/OpenVanilla.app/Contents/Resources/DataTables/AssociatedPhrases/associated-phrases.cin`，會讓 macOS 認為 `OpenVanilla.app` 損毀了 (簽章驗證工具會說 "a sealed resource is missing or invalid")。
> 
> 要能夠自訂 `associated-phrases.cin` 的內容，有兩條途徑：
> 
> 1. 要不就是自己裝 Xcode 然後 git clone OpenVanilla 的原始碼，自己編譯安裝，這樣想怎麼改就可以怎麼改
> 2. 修改 `OVModuleManager.mm` 或是 `OVAFAssociatedPhrases.cpp` 讓聯想詞模組可以在有 user override file 的情況下，優先採用用戶提供的檔案

謝謝解答，唯有弄好了再fork一個吧

另外關於windows自帶的關聯詞庫，有方法Dump出來嗎？ 記得xp還win7的時候能自己編輯關聯詞庫，但年代太久遠了沒什麼印象

要是不能把windows的關聯詞庫搞到手估計光弄詞庫就夠嗆。。

**Comment by lukhnos** [comment]
> 另外關於windows自帶的關聯詞庫，有方法Dump出來嗎？ 記得xp還win7的時候能自己編輯關聯詞庫，但年代太久遠了沒什麼印象

這恐怕得請你自行研究了。OpenVanilla 的聯想詞庫是從小麥注音來的，常用詞跟詞頻都反映的是台灣的中文用法，這其中也還有資料授權的考量。

**Comment by hoho97** [comment]
姑且算是自己重新編譯把聯想詞順序改成Windows的了。
有需要的朋友（主要是香港朋友吧，畢竟從小就學windows速成倉頡）可以自己來下，OV官方版更新了的話我也會跟上的

https://github.com/hoho97/openvanilla-kai
