### ISSUE TITLE
Code signature change in version 1.6.2?

### ISSUE THREAD

**Issue by suschizu** [openvanilla/openvanilla#54]
Hello!
I've received a notification that the code signature changed in download: https://github.com/openvanilla/openvanilla/releases/download/1.6.2/OpenVanilla-Installer-Mac-1.6.2.zip

EXPECTED Lukhnos Liu (PYD935QB58) but FOUND Lukhnos Liu (JK5M8ENA23)
can you confirm it?

**Comment by lukhnos** [comment]
Would you mind telling me what is the tool that informed you about the signature change?

To your question: yes, I can confirm that that's expected. Version 1.6.1 is the only version that was signed with `PYD935QB58` but version 1.6.2 was signed with `JK5M8ENA23`.

**Comment by suschizu** [comment]
Great thanks for the information! I’m working for an app called MacUpdater - I’m running security checks over all updates that appear in our database and checking the code signature is one of them - It’s just 'code sign -dv'
