### ISSUE TITLE
請教一下怎樣給選字框加上 macOS Spotlight 視窗那樣的亮邊？

### ISSUE THREAD

**Issue by ShikiSuen** [openvanilla/openvanilla#55]
包括小麥注音在內，OV 預設的選字框好像都是黑邊框。
我不是太喜歡預設配色在 macOS 暗黑模式下的表現，就嘗試改顏色。
結果我沒能找到哪裡可以改候選框的邊框的顏色。
目前的黑色邊框真的讓候選窗格在某些視窗上下文場合內的辨識度超低。

<img width="473" alt="截圖 2021-11-27 22 32 30" src="https://user-images.githubusercontent.com/3164826/143685703-472b8b27-8bd6-49ee-9440-e4b7c4ff9264.png">

另外，順道請教一下視窗的 padding 與圓角能在哪裡改？
<img width="208" alt="截圖 2021-11-27 22 33 52" src="https://user-images.githubusercontent.com/3164826/143685790-2c8620e6-d9a4-4bdc-9f21-87b4bf5eb7a7.png">
RIME 鼠鬚管的 Padding 倒是滿對我胃口。

**Comment by zonble** [comment]
https://github.com/openvanilla/openvanilla/blob/6c6703c93023f0b59c62e7a7ef0bafe6413767c1/Libraries/Voltaire/Voltaire/VTHorizontalCandidateView.m#L106-154

https://github.com/openvanilla/openvanilla/blob/deeb767e7af30b22ccd872928e56323e89f54a1f/Libraries/Voltaire/Voltaire/VTVerticalKeyLabelStripView.m#L47-87

在對背景做 fillRect 之後，再選個顏色 strokeRect。

**Comment by ShikiSuen** [comment]
拿小麥注音的引擎測試了一下。
亮邊並未施加到整個選字窗體本身，但至少辨識度問題解決了。感謝 zonble。

<img width="380" alt="截圖 2021-12-05 11 27 19" src="https://user-images.githubusercontent.com/3164826/144732281-d12c373f-f6ae-4122-b9c5-a8c2ccbdc4f2.png">
<img width="122" alt="截圖 2021-12-05 11 32 05" src="https://user-images.githubusercontent.com/3164826/144732377-cec97d6b-d1c4-40cb-9b44-6a2c5d237eaa.png">

**Comment by ShikiSuen** [comment]
我先關掉這個 issue，畢竟這算是我在美術方面的私慾。到目前這一步，就已經不能說這是 hard issue 了。
但是這個話題可以繼續討論下去。

**Comment by ShikiSuen** [comment]
我發現了更好的解決方案。詳見：https://github.com/openvanilla/openvanilla/pull/56

<img width="399" alt="人" src="https://user-images.githubusercontent.com/3164826/144745674-84f93235-90bc-4e48-80e7-baf7070e3e2e.png">
