### ISSUE TITLE
讓行列輸入法支援英數字鍵盤配置

### ISSUE THREAD

**Issue by aethanyc** [openvanilla/openvanilla#6]
我是 Dvorak 英文鍵盤跟行列輸入法使用者。目前行列輸入法只支援「特別碼提示」跟「快打模式」兩種設定，其餘輸入法如倉頡皆有支援英數字鍵盤配置，可切換為 Dvorak，如下圖。能否為行列也加入英數字鍵盤配置？

我已試過在「一般設定」下，改英數字鍵盤配置為 Dvorak，在行列輸入法下按 shift 打字，出的鍵仍是 Qwerty 配置。

![2015-03-25 11 16 41](https://cloud.githubusercontent.com/assets/102858/6817796/a396c444-d2e0-11e4-8d54-128c67ff6ae5.png)

**Comment by lukhnos** [comment]
不好意思現在才回覆這一張 ticket。我竟然忘記了其實行列模組是有隱藏設定可用的（而且程式從 2012 年 10 月就存在了）。請在終端機下輸入：

```
defaults write org.openvanilla.OVIMArray AlphanumericKeyboardLayout com.apple.keylayout.Dvorak
```

要復原的話，換回 US keyboard layout 就可以：

```
defaults write org.openvanilla.OVIMArray AlphanumericKeyboardLayout com.apple.keylayout.US
```

**Comment by aethanyc** [comment]
很高興知道有這個設定！但經我測試，行列如果用這個方法設定成 `Dvorak`之後，按 shift 後打出的英文是正確的 `Dvorak` 鍵位，但中文的出鍵就亂掉了。似乎行列的鍵位跟`US`的鍵位是綁定的。

**Comment by lukhnos** [comment]
啊，我原先還在好奇，行列的鍵盤配置不是與英文鍵盤配置無關嗎？我終於看懂，是說希望行列在按 Shift 後打出來的英文是依照 Dvorak 排列嗎？

其實 OV 一般設定中的英數字鍵盤配置，只有在 Caps Lock 打開時有用。如果倉頡設定為 Dvorak，則行為跟行列使用隱藏設定的結果是一樣的（中文及英數字都變成了 Dvorak）。確實要解決這個問題，那要像小麥注音那樣，中文及英數字的鍵盤排列要分開設定才行。

**Comment by aethanyc** [comment]
> 啊，我原先還在好奇，行列的鍵盤配置不是與英文鍵盤配置無關嗎？我終於看懂，是說希望行列在按 Shift 後打出來的英文是依照 Dvorak 排列嗎？

對的，如果能這樣就太棒了。

**Comment by idhowardgj94** [comment]
不好意思，我最近因為工作的關係要用mac開發，本身是dvorak加行列的使用者，
剛剛發現這個問題還是沒有解決，請問有辦法解決嗎

**Comment by zonble** [comment]
在 rev 35ae88f2cc581416abfca98744b8ee8b37694de1 當中，可以允許行列輸入法與英數輸入法使用不同的 layout。
