### ISSUE TITLE
功能建議：OpenVanilla 對於「數字鍵」做為字根鍵的處理

### ISSUE THREAD

**Issue by gontera** [openvanilla/openvanilla#60]
最近我嘗試製作純以數字作為輸入字根的行列10鍵數字輸入法（行列10）array10b.cin，在使用「加入新輸入法」的功能匯入 OpenVanilla 1.6.2 的過程中，發現 OpenVanilla 不支援使用右邊的數字鍵盤做為字根鍵，而僅能使用左邊上排的數字鍵，使用上頗為不便。一些使用「數字」做為字根鍵的輸入法，如行列10、三角號碼、四角號碼等輸入法，如能完全使用右邊數字鍵盤做為輸入文字的字根鍵，而左邊上排的數字鍵則純用於輸入數字，應是較理想的設計。

因此，我建議 OpenVanilla 能夠將「右邊數字鍵盤」與「左邊上排數字鍵」分開處理，最好能夠增加選擇項，提供使用者自行定義要使用哪一邊的數字鍵做為字根鍵。譬如：

* 注音、大易輸入法：使用左邊上排數字鍵做為字根鍵，右邊數字鍵盤則用於輸入數字。
* 行列10、三角號碼、四角號碼輸入法：使用右邊數字鍵盤做為字根鍵，左邊上排數字鍵則用於輸入數字。

在此一併提供我試做的 array10b.cin 原始檔供參。
[array10b-openvanilla-test.cin.zip](https://github.com/openvanilla/openvanilla/files/8457301/array10b-openvanilla-test.cin.zip)

**Comment by lukhnos** [comment]
感謝回報。我原本以為是局限於行列模組的問題，但這樣看來表格輸入法模組一樣需要修正。

**Comment by lukhnos** [comment]
@gontera 剛剛發布了 1.6.3 版，除了更新了行列表格 (#59) ，也增加了一個隱藏設定，可以指定使用數字鍵盤的數字鍵當字根鍵。

例如使用上述的測試  .cin 檔，匯入後，在終端機下輸入以下指令，就可以開啟隱藏功能：

```
defaults write org.openvanilla.OVIMTableBased.array10b-openvanilla-test OnlyUseNumPadNumbersForRadicals -string true
```

開啟後，鍵盤左方上排數字鍵就只能輸入數字。這個設定的實際作用是「把鍵盤左方跟數字鍵盤的用途對調過來」。

請測試看看這樣是否合用。

**Comment by lukhnos** [comment]
1.6.3 版下載網址: https://github.com/openvanilla/openvanilla/releases/download/1.6.3/OpenVanilla-Installer-Mac-1.6.3.zip

**Comment by gontera** [comment]
> @gontera 剛剛發布了 1.6.3 版，除了更新了行列表格 (#59) ，也增加了一個隱藏設定，可以指定使用數字鍵盤的數字鍵當字根鍵。
> 
> 例如使用上述的測試 .cin 檔，匯入後，在終端機下輸入以下指令，就可以開啟隱藏功能：
> 
> ```
> defaults write org.openvanilla.OVIMTableBased.array10b-openvanilla-test OnlyUseNumPadNumbersForRadicals -string true
> ```
> 
> 開啟後，鍵盤左方上排數字鍵就只能輸入數字。這個設定的實際作用是「把鍵盤左方跟數字鍵盤的用途對調過來」。
> 
> 請測試看看這樣是否合用。

感謝，終端機內打入指令後果然就可以了，但又再衍生出一個問題，不知是否能夠解決？就是遇到重碼字時，必須按 Space 後才會顯示選字框；但因為右邊的數字鍵盤並沒有 Space，所以左手仍必須不時待命以便按下 Space，仍是有點不便。此時，若能夠將 Enter 鍵定義為與 Space 的作用一樣，那就完美了。

其實還有變通的方法，就是利用數字鍵的 "+" 符號做為 endkey（按鍵面積大，比較好按），只是 .cin 檔案的內容就必須配合做調整了。
