### ISSUE TITLE
功能建議：希望 OpenVanilla 能支援以 Enter 做為組字鍵

### ISSUE THREAD

**Issue by gontera** [openvanilla/openvanilla#62]
延續 #60 的話題。

終端機內打入指令雖可以使用數字鍵做為字根，但又再衍生出一個問題，不知是否能夠解決？就是在 OpenVanilla 中遇到重碼字時，必須按 Space 後才會顯示選字框；但因為右邊的數字鍵盤並沒有 Space，所以左手仍必須不時待命以便按下 Space，仍有點不便。此時，若能夠將數字鍵盤中的 Enter 鍵定義為與 Space 的作用一樣做為送字使用，那就完美了。

其實還有變通的方法，就是利用數字鍵的 "+" 符號做為 endkey（按鍵面積大，比較好按），只是 .cin 檔案的內容就必須配合做調整了。

**Comment by lukhnos** [comment]
> 就是在 OpenVanilla 中遇到重碼字時，必須按 Space 後才會顯示選字框

如果啟用表格輸入法「一邊打字一邊組字」的選項，可以解決這個問題嗎？還是這跟行列 10 預期的行為不一樣呢？

> 此時，若能夠將數字鍵盤中的 Enter 鍵定義為與 Space 的作用一樣做為送字使用，那就完美了。

Ok, 這個看來也是過去沒有考慮到的地方，因為英數字鍵盤的 Return 是有處理的，但是數字鍵盤的 Enter 卻沒有。

**Comment by lukhnos** [comment]
@gontera 發布了 1.6.4 版，Enter 鍵等同於 Return 鍵了: https://github.com/openvanilla/openvanilla/releases/download/1.6.4/OpenVanilla-Installer-Mac-1.6.4.zip

**Comment by gontera** [comment]
> 如果啟用表格輸入法「一邊打字一邊組字」的選項，可以解決這個問題嗎？還是這跟行列 10 預期的行為不一樣呢？
啟用 OpenVanilla 的「一邊打字一邊組字」項目時，使用行列10將有非預期的結果，不建議使用。

例如，當我想輸入「葉」字時（字根碼為 441248），OpenVanilla 會攔截開頭的 44 並將「卉」送出（「卉」的字根碼為 44），造成後續的字根碼未能完成輸入。

> Ok, 這個看來也是過去沒有考慮到的地方，因為英數字鍵盤的 Return 是有處理的，但是數字鍵盤的 Enter 卻沒有。
太感謝了，OpenVanilla 更新為 1.6.4 版以後，行列10的表現就完全正常了！

**Comment by tzu1069** [comment]
mac12.5.1 版本，OpenVanilla 版本1.6.4 大易輸入法的輸入， 在各個軟體、以及網頁操作 輸入文字時 ， 都無法呈現完整文字，請問這應該如何 解決呢？
