### ISSUE TITLE
Mac 右上角的 OpenVanilla 輸入法變成灰色無法選中時，有什麽方法可以高效恢復？

### ISSUE THREAD

**Issue by holucas** [openvanilla/openvanilla#64]
首先感謝 Lukhnos 和各位大大打造了這麼好用的一個輸入法！用了三年半，很好地解決了我打倉頡但要出簡體字的訴求

(估計本質上是 Mac 問題) 最近 OV 較頻繁會在非登出的情況下變成灰色不可選擇，之前可以通過登出再登入來解決，但最近也解決不了。有沒有什麼方法可以解決这個問題？（除了重启電腦，比較多网頁需要開着，重启成本較大）

**Comment by lukhnos** [comment]
請教幾個問題：

1. 您使用的 macOS 版本為何？
2. 當 OV 變成灰色無法選擇時，是否在使用 Terminal.app / iTerms 等終端機軟體？
3. 您的 Mac 是工作場合配發的機器嗎？是否有公司設定的 device management policy?

**Comment by lukhnos** [comment]
我一直有個印象，在用 Catalina 時確實容易出現第三方輸入法被 disable 的問題（不只是 OV 會遇到），但是後來 Big Sur 之後的版本修正了。後來遇到的問題多半跟終端機的「加密的鍵盤輸入」有關，看一下[小麥注音相關 FAQ 裡面的說明](https://github.com/openvanilla/McBopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C#%E5%B0%8F%E9%BA%A5%E6%B3%A8%E9%9F%B3%E5%9C%96%E7%A4%BA%E5%9C%A8%E8%BC%B8%E5%85%A5%E6%B3%95%E9%81%B8%E5%96%AE%E4%B8%8A%E8%AE%8A%E6%88%90%E7%81%B0%E8%89%B2%E7%84%A1%E6%B3%95%E5%88%87%E6%8F%9B%E9%81%8E%E5%8E%BB%E6%80%8E%E9%BA%BC%E8%BE%A6) 對您有沒有幫助。

至於 device management policy，如果能跟公司 IT 部門詢問，應該就能知道。我在這方面了解有限，實在不知道當前 IT 在 macOS 上能夠設定多少 policy restriction。但我知道有些人工作配發機器上的 Terminal.app 總是將 Secure Keyboard Entry 開啟的。然後 Terminal.app 可能會把關閉第三方輸入法的狀態「傳染」給其他的 app process。

**Comment by zonble** [comment]
現在已經到 macOS 15 了，這張票有點舊，先關掉好了。
