### ISSUE TITLE
更新系統後，右上角的 OpenVanilla 輸入法變成灰色，無法使用

### ISSUE THREAD

**Issue by IvesShe** [openvanilla/openvanilla#65]
前幾天更新到Monterey 12.5.1之後，右上角OpenVanilla就變灰色無法使用，刪除之後重開機、再重新安裝，問題依舊，有人有一樣的狀況嗎？

**Comment by tzu1069** [comment]
mac 更新後，無法正常輸入文字， 重新移除OpenVanilla 在安裝，問題依然存在，只要使用OpenVanilla 大 易輸入法，所有的軟體文字輸入都無法正常運作，不知道應該要如何解決？

**Comment by whtang906** [comment]
12.6.5也有這個問題

**Comment by zonble** [comment]
現在已經到 macOS 15 了，這張票有點舊，先關掉好了。
