### ISSUE TITLE
行列30 v2023-1.0 新版鍵碼表

### ISSUE THREAD

**Issue by gontera** [openvanilla/openvanilla#67]
行列30 已於 2023/02/11 釋出新版鍵碼表，版號 v2023-1.0，敬請 OpenVanilla 下次更版時可以納入。

行列30 鍵碼表官網：[https://github.com/gontera/array30](https://github.com/gontera/array30)
行列30 for OpenVanilla 鍵碼表網址：[https://github.com/gontera/array30/tree/master/OpenVanilla](https://github.com/gontera/array30/tree/master/OpenVanilla)

非常感謝！

**Comment by lukhnos** [comment]
感恩！
