### ISSUE TITLE
是否支持 Opt+某一按键输入字符的方式？

### ISSUE THREAD

**Issue by starkshaw** [openvanilla/openvanilla#69]
Hello,

我在设计一个类似土耳其语的键盘，在土耳其语键盘中，可以使用 Opt （或者Windows 上面的右Alt键）来定义一些在该语言中常见的字符，比如：

```
Opt + G = Ğ
Opt + g = ğ
Opt + O = Ö
Opt + U = Ü
Opt + I = İ
Opt + i = ı
```

Openvanilla 是否支持这样的定义方式？

**Comment by lukhnos** [comment]
OV 的表格輸入模組，一直以來都設計為「輸入拉丁字符，輸出表格對照的鍵值」，沒有考慮到 Opt/Alt/AltGr 等組合鍵這類的模式。

有試過 Ukelele (https://software.sil.org/ukelele/) 一類的解決方案嗎？

**Comment by starkshaw** [comment]
谢谢您的帮助，的确可以通过 ukelele 做到我想要的需求。
