### ISSUE TITLE
關聯詞輸入

### ISSUE THREAD

**Issue by mahiuchun** [openvanilla/openvanilla#7]
As title.

**Comment by peteroid** [comment]
+1

**Comment by lukhnos** [comment]
I finally got some time to revive a branch made in 2013 [here](https://github.com/openvanilla/openvanilla/commits/v1.3-work) and created a side-build. It still has some rough edges, but would you be interested in giving it a try? You can build from the source or mail to `ovadmin at openvanialla dot org` for a download link.

Announcement at https://groups.google.com/forum/#!topic/openvanilla/F4H7vD6iq9o

**Comment by lukhnos** [comment]
This is now built-in in 1.3.0: https://github.com/openvanilla/openvanilla/releases/tag/1.3.0
