### ISSUE TITLE
自訂的cin檔，可以調詞頻嗎？

### ISSUE THREAD

**Issue by xerothermic** [openvanilla/openvanilla#81]
你好，我最近在研究自己生成cin檔，目前可以做出一個堪用的cin檔。
我選了"While typing, show candidate list if there are candidates"，來產生候選字。
不知道有沒有辦法讓這些候選字，依照一些自訂義的詞頻來決定出現的位子?

**Comment by lukhnos** [comment]
> 不知道有沒有辦法讓這些候選字，依照一些自訂義的詞頻來決定出現的位子?

`%chardef` 段落中的條目順序，就是候選字詞的順序了。例如：

```
%chardef begin
aa 候
aa 選
bb 字
aa 詞
%chardef end
```

於是打 `aa` 時，選字窗會根據上述順序，列出「候」「選」「詞」三個選項。

**Comment by xerothermic** [comment]
感謝！
