### ISSUE TITLE
選字區有重複的選項?

### ISSUE THREAD

**Issue by xerothermic** [openvanilla/openvanilla#82]
我剛剛發現一個奇怪的現象，用我自創的cin檔，裡面有一個字(拼法:e5)，可以有六種結果。我的selkey是"qwdzxyv" 但是選字區先出現四組字，然後又重複從第一個字開始，然後才把所有的字顯示出來。請問這是個已知的問題嗎？

一開始：
<img width="95" alt="image" src="https://github.com/openvanilla/openvanilla/assets/575831/40fe3dd3-c13a-4b74-bb0e-66faa305bff5">
把選字區，按到第二頁：
<img width="98" alt="image" src="https://github.com/openvanilla/openvanilla/assets/575831/878ebca1-30cc-41c3-98e9-c82de362bfbb">

**Comment by xerothermic** [comment]
如果需要，我可以提供repro的cin檔

**Comment by lukhnos** [comment]
這確實奇怪，因為你的選字鍵有七個。如果只有六個候選字詞，結果應該只有一頁、六個選項。

請問 repo 是公開的嗎？如果是，煩請提供網址跟 .cin 取得方式。另外也請提供你的 OV 自訂 cin 設定（例如有開啟「一邊打字一邊組字」選項等等）。

**Comment by tianjianjiang** [comment]
也許那個 ê 是 combining characters?

**Comment by xerothermic** [comment]
cin file: https://github.com/xerothermic/word2cin/releases/tag/dev-0.1.0
repo: https://github.com/xerothermic/word2cin

可以用：
```
% egrep -n '^e5 ' build/two-dict-tailo.cin
54:e5 ê
56:e5 个
4629:e5 的
6450:e5 鞋
8349:e5 個
8647:e5 暝
```

**Comment by xerothermic** [comment]
不好意思，看起來是cin處理的不乾淨。我剛剛再確認一次，把cin dedup，然後重新加入OV，現在沒有重複的選字了
