### ISSUE TITLE
升級 OS 15.0.1 Sequoia 後終端機無法上字

### ISSUE THREAD

**Issue by chuanghs** [openvanilla/openvanilla#84]
作業系統版本: 15.0.1
輸入法: 行列

應用程式: 終端機、Moneydance
問題情況: 輸入任何字碼 (ex: gg8 )，組字框消失，但未出現應出現的「碼」字

**Comment by zonble** [comment]
過去的內建終端機有一個問題，導致香草輸入法需要做一些延後處理，才可以將文字送到終端機當中。但是在 macOS 15.0.1 之後，看起來蘋果官方把那個問題修好了，我們的延遲處理反而無法讓字沒辦法送到終端機。因此我們在 macOS 15.0.1 之後取消這個判斷。

這個修正放在 584e66aef9f8c738c8cc107376afa51d38cb8801 中。

**Comment by zonble** [comment]
Moneydance 的問題需要再看一下。

**Comment by zonble** [comment]
> Moneydance 的問題需要再看一下。

我自己試了一下，目前看不出有什麼問題。

**Comment by lukhnos** [comment]
請下載 1.7.0 應該就不會再有這個問題: https://github.com/openvanilla/openvanilla/releases/download/1.7.0/OpenVanilla-Installer-Mac-1.7.0.zip
