### ISSUE TITLE
聯想詞快捷鍵對應錯誤

### ISSUE THREAD

**Issue by sunnymiu** [openvanilla/openvanilla#91]
各位好，聯想詞功能在 1.7.0 下出現鍵盤快捷鍵對應錯誤的問題

以輸入「你」字為例，界面會提示以下聯想詞：

１２３４５６７８９
們的要是有說在會想

要是聯想詞選擇鍵設定成「Shift 1–9」或「Shift 1–0」
第二個聯想詞並不是落在第二個選擇鍵，而是跳了一個鍵，落在第三

假設輸入「你」字的具體結果會是：
1→們
**2→＠**
3→的
4→要
5→是
6→有
7→說
8→在
9→會
0→想或「）」（視乎有沒有開啟 Shift 0）

希望各位能看看是否有這個問題及協助修正，謝謝！

**Comment by lukhnos** [comment]
Fixed in https://github.com/openvanilla/openvanilla/pull/92

**Comment by lukhnos** [comment]
1.7.1 版修正了這個問題，安裝後，從 OpenVanilla 偏好設定那邊修改聯想詞按鍵，就可以正確使用 Shift 1-9 或 Shift 1-0 了。

**Comment by chun1324** [comment]
在1.8.4上面遇到同一問題, Shift+2無法挑選關聯字, 輸出成@

<img width="167" height="208" alt="Image" src="https://github.com/user-attachments/assets/40a124a9-59c5-40fb-9885-2b1f0f75bd42" />

後來重新裝 1.7.2, 重新設置section keys為Shift1~Shift9 即回復正常
